import { defineStore } from "pinia";

export const useTeachersStudentsStore = defineStore(
  "teachersStudents-store",
  () => {
    const classrooms = ref<ClassroomModule[]>([
      {
        id: "670484455867",
        moduleId: "",
        moduleInstance: "BT MT",
        moduleTitle: "INFO Betreuer BT MT 24",
        trimester: "TM 2024-2",
        raw: {
          id: "670484455867",
          name: "INFO Betreuer BT MT 24",
          section: "TM 2024-2 BT MT",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          ownerId: "106954446329401515421",
          creationTime: "2024-03-20T17:48:28.630Z",
          updateTime: "2024-03-20T17:48:28.630Z",
          enrollmentCode: "har6exv",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjcwNDg0NDU1ODY3",
          teacherGroupEmail:
            "INFO_Betreuer_BT_MT_24_TM_2024_2_BT_MT_teachers_56ef7e9e@edu.accadis.com",
          courseGroupEmail:
            "INFO_Betreuer_BT_MT_24_TM_2024_2_BT_MT_87a1f774@edu.accadis.com",
          teacherFolder: {
            id: "1bhExQaOcV521tBMpP6NzZRk0l994xOkLRka1EoAnrXV9PvlC6e9RVvVq2f8GylCvZyiiRNt9",
            title: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
            alternateLink:
              "https://drive.google.com/drive/folders/1bhExQaOcV521tBMpP6NzZRk0l994xOkLRka1EoAnrXV9PvlC6e9RVvVq2f8GylCvZyiiRNt9",
          },
          guardiansEnabled: false,
          calendarId: "c_classroome495fc40@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "INFO",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "668079603941",
        moduleId: "",
        moduleInstance: "BT MT",
        moduleTitle: "INFO Betreuer BT MT 24",
        trimester: "TM 2024-2",
        raw: {
          id: "668079603941",
          name: "Test-Classroom (geändertAL)",
          section: "für AL zum Testen (geändert AL)",
          descriptionHeading: "Test-Classroom für AL zum Testen",
          description: "Hier werden nur Tests stattfinden",
          room: "Konfi1",
          ownerId: "106954446329401515421",
          creationTime: "2024-03-08T08:43:16.663Z",
          updateTime: "2024-03-08T13:36:10.053Z",
          enrollmentCode: "pt4khpp",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjY4MDc5NjAzOTQx",
          teacherGroupEmail:
            "Test_Classroom_f_r_AL_zum_Testen_teachers_64befa5c@edu.accadis.com",
          courseGroupEmail:
            "Test_Classroom_f_r_AL_zum_Testen_b2a9b049@edu.accadis.com",
          teacherFolder: {
            id: "1XkRxIbiPdDnsJ_3dwZwoGgSqJUkH98Y_zKJP5fZjmHDnYyRrg73s1f0VyQ8ZCgyD8VB-xawL",
            title: "Test-Classroom für AL zum Testen",
            alternateLink:
              "https://drive.google.com/drive/folders/1XkRxIbiPdDnsJ_3dwZwoGgSqJUkH98Y_zKJP5fZjmHDnYyRrg73s1f0VyQ8ZCgyD8VB-xawL",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom9d839574@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: false,
        type: "UNCLASSIFIED",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },

      {
        id: "655800375454",
        moduleId: "",
        moduleInstance: "BT MT",
        moduleTitle: "INFO Betreuer BT MT 24",
        trimester: "TM 2024-2",
        raw: {
          id: "655800375454",
          name: "Career Day 2024 (Internationals)",
          section: "CD 2024 INT",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          ownerId: "112876078907940160165",
          creationTime: "2024-03-06T18:12:44.276Z",
          updateTime: "2024-03-19T14:31:50.827Z",
          enrollmentCode: "2yvqkmv",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjU1ODAwMzc1NDU0",
          teacherGroupEmail:
            "Career_Day_2024_Internationals_CD_2024_INT_teachers_2430a305@edu.accadis.com",
          courseGroupEmail:
            "Career_Day_2024_Internationals_CD_2024_INT_5532f2d6@edu.accadis.com",
          teacherFolder: {
            id: "1LAsmL2fsCtvRblmlWpy5fEc2uka_r90kxbpf2m4MHq9lksjeYy8FCy84M8fo3j8eIRXXEcAg",
          },
          guardiansEnabled: false,
          calendarId: "c_classroomf9ae8a2e@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: false,
        type: "UNCLASSIFIED",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "667710636324",
        moduleId: "",
        moduleInstance: "BT MT",
        moduleTitle: "INFO Betreuer BT MT 24",
        trimester: "TM 2024-2",
        raw: {
          id: "667710636324",
          name: "Career Day 2024 (FT)",
          section: "CD 2024 FT",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          ownerId: "112876078907940160165",
          creationTime: "2024-03-06T18:12:43.300Z",
          updateTime: "2024-03-19T14:31:30.427Z",
          enrollmentCode: "zdzzzoh",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjY3NzEwNjM2MzI0",
          teacherGroupEmail:
            "Career_Day_2024_FT_CD_2024_FT_teachers_285b4395@edu.accadis.com",
          courseGroupEmail:
            "Career_Day_2024_FT_CD_2024_FT_3aeaf9a6@edu.accadis.com",
          teacherFolder: {
            id: "13I2UCly2bfP3jbWbRjikM-7gqjYUB49kkjYV-MJDfirkyNezqcVT9BA1R2aWSr-JgLBpxka2",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom0e0fbc9d@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: false,
        type: "UNCLASSIFIED",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "667711707543",
        moduleId: "",
        moduleInstance: "BT MT",
        moduleTitle: "INFO Betreuer BT MT 24",
        trimester: "TM 2024-2",
        raw: {
          id: "667711707543",
          name: "Career Day 2024 (DS/PT)",
          section: "CD 2024 DS+PT",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          ownerId: "112876078907940160165",
          creationTime: "2024-03-06T18:12:42.954Z",
          updateTime: "2024-03-19T14:31:09.154Z",
          enrollmentCode: "h7fqq4i",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjY3NzExNzA3NTQz",
          teacherGroupEmail:
            "Career_Day_2024_DS_PT_CD_2024_DS_PT_teachers_0321e435@edu.accadis.com",
          courseGroupEmail:
            "Career_Day_2024_DS_PT_CD_2024_DS_PT_0c924065@edu.accadis.com",
          teacherFolder: {
            id: "1aIsjFDEhYT_YiwHWFZHp62UpgJaS8Eg6TxE36MT0jfrjgzkOh2OEcqB8M5G-2yzRQ5sMb5aG",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom3c2a1399@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: false,
        type: "UNCLASSIFIED",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "628183650317",
        moduleId: "PRO 302",
        moduleInstance: "BT PT",
        moduleTitle: "Bachelor Thesis",
        trimester: "TM 2024-2",
        raw: {
          id: "628183650317",
          name: "PRO 302 Bachelor Thesis",
          section: "TM 2024-2 BT PT",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-22T11:26:46.936Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-01-22T11:26:46.936Z",
          enrollmentCode: "eobjfcx",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjI4MTgzNjUwMzE3",
          teacherGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_PT_teachers_50256f89@edu.accadis.com",
          courseGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_PT_4c3be7e8@edu.accadis.com",
          teacherFolder: {
            id: "1hOHdzQqSy3oomyW3IQxiRLDlLAieXWMS87SI_YBQkKfbXcGRqOQHpco3NHGX7WMQ-PbxKnAw",
            title: "PRO 302 Bachelor Thesis TM 2024-2 BT PT",
            alternateLink:
              "https://drive.google.com/drive/folders/1hOHdzQqSy3oomyW3IQxiRLDlLAieXWMS87SI_YBQkKfbXcGRqOQHpco3NHGX7WMQ-PbxKnAw",
          },
          guardiansEnabled: false,
          calendarId: "c_classroomfcfd0e4f@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },

      {
        id: "628183590487",
        moduleId: "PRO 302",
        moduleInstance: "BT",
        moduleTitle: "Bachelor Thesis",
        trimester: "TM 2024-2",
        raw: {
          id: "628183590487",
          name: "PRO 302 Bachelor Thesis",
          section: "TM 2024-2 BT",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-22T11:26:46.851Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-01-22T11:26:46.851Z",
          enrollmentCode: "523zcbo",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjI4MTgzNTkwNDg3",
          teacherGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_teachers_e3b52feb@edu.accadis.com",
          courseGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_d93ca60f@edu.accadis.com",
          teacherFolder: {
            id: "1FFaHexWWMv9ELFEIVIo5v_k9PlNXYbHryrnxfKCozanwKQ-nHEGLFjJA-88PAzVPsCY50l2B",
            title: "PRO 302 Bachelor Thesis TM 2024-2 BT",
            alternateLink:
              "https://drive.google.com/drive/folders/1FFaHexWWMv9ELFEIVIo5v_k9PlNXYbHryrnxfKCozanwKQ-nHEGLFjJA-88PAzVPsCY50l2B",
          },
          guardiansEnabled: false,
          calendarId: "c_classroomde670b2e@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "628072754124",
        moduleId: "PRO 302",
        moduleInstance: "BT",
        moduleTitle: "Bachelor Thesis",
        trimester: "TM 2024-2",
        raw: {
          id: "628183590487",
          name: "PRO 302 Bachelor Thesis",
          section: "TM 2024-2 BT",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-22T11:26:46.851Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-01-22T11:26:46.851Z",
          enrollmentCode: "523zcbo",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjI4MTgzNTkwNDg3",
          teacherGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_teachers_e3b52feb@edu.accadis.com",
          courseGroupEmail:
            "PRO_302_Bachelor_Thesis_TM_2024_2_BT_d93ca60f@edu.accadis.com",
          teacherFolder: {
            id: "1FFaHexWWMv9ELFEIVIo5v_k9PlNXYbHryrnxfKCozanwKQ-nHEGLFjJA-88PAzVPsCY50l2B",
            title: "PRO 302 Bachelor Thesis TM 2024-2 BT",
            alternateLink:
              "https://drive.google.com/drive/folders/1FFaHexWWMv9ELFEIVIo5v_k9PlNXYbHryrnxfKCozanwKQ-nHEGLFjJA-88PAzVPsCY50l2B",
          },
          guardiansEnabled: false,
          calendarId: "c_classroomde670b2e@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "628072754124",
        moduleId: "PRO 503",
        moduleInstance: "MT",
        moduleTitle: "505 Master Thesis TM 2024-1 MT",
        trimester: "TM 2024-1",
        raw: {
          id: "628072754124",
          name: "PRO 503/505 Master Thesis TM 2024-1 MT",
          section: "TM 2024-1 MT",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-17T09:11:22.469Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-01-17T09:11:22.469Z",
          enrollmentCode: "3fzhone",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjI4MDcyNzU0MTI0",
          teacherGroupEmail:
            "PRO_503_505_Master_Thesis_TM_2024_1_MT_TM_2024_1_MT_teachers_f1d01b63@edu.accadis.com",
          courseGroupEmail:
            "PRO_503_505_Master_Thesis_TM_2024_1_MT_TM_2024_1_MT_04f1ccec@edu.accadis.com",
          teacherFolder: {
            id: "1KWs0zO_lchkwxrqy0Y3Lyuu-2EPRXw-1ng_hljKfsFz3Cwkyy8u_4odca2CzvRxcu27Xkcur",
            title: "PRO 503/505 Master Thesis TM 2024-1 MT TM 2024-1 MT",
            alternateLink:
              "https://drive.google.com/drive/folders/1KWs0zO_lchkwxrqy0Y3Lyuu-2EPRXw-1ng_hljKfsFz3Cwkyy8u_4odca2CzvRxcu27Xkcur",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom26c1838f@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },

      {
        id: "647180924156",
        moduleId: "FUS 201",
        moduleInstance: "FuS II",
        moduleTitle: "Future Skills II PED",
        trimester: "TM 2024-1",
        raw: {
          id: "647180924156",
          name: "FUS 201 Future Skills II PED",
          section: "TM 2024-1 FuS II-LS",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-15T22:09:38.943Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-03-06T09:36:01.601Z",
          enrollmentCode: "gamrpes",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjQ3MTgwOTI0MTU2",
          teacherGroupEmail:
            "FUS_201_Future_Skills_II_PED_TM_2024_1_FuS_II_LS_teachers_0735793e@edu.accadis.com",
          courseGroupEmail:
            "FUS_201_Future_Skills_II_PED_TM_2024_1_FuS_II_LS_f944d7a6@edu.accadis.com",
          teacherFolder: {
            id: "1gkQviqkMFy2TTx0H4rvv6lXvDRcCT-jFIHMX3iWlDDYncc7sMMLUlcvVw8NZD-wNDeazezQ3",
            title: "FUS 201 Future Skills II PED TM 2024-1 FuS II-LS",
            alternateLink:
              "https://drive.google.com/drive/folders/1gkQviqkMFy2TTx0H4rvv6lXvDRcCT-jFIHMX3iWlDDYncc7sMMLUlcvVw8NZD-wNDeazezQ3",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom656732e5@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
      {
        id: "647181096351",
        moduleId: "FUS 201",
        moduleInstance: "FuS II",
        moduleTitle: "Future Skills II",
        trimester: "TM 2024-1",
        raw: {
          id: "647181096351",
          name: "FUS 201 Future Skills II",
          section: "TM 2024-1 FuS II-SM",
          ownerId: "106954446329401515421",
          creationTime: "2024-01-15T22:09:37.125Z",
          descriptionHeading: "INFO Betreuer BT MT 24 TM 2024-2 BT MT",
          updateTime: "2024-01-15T22:09:37.125Z",
          enrollmentCode: "4r6isov",
          courseState: "ACTIVE",
          alternateLink: "https://classroom.google.com/c/NjQ3MTgxMDk2MzUx",
          teacherGroupEmail:
            "FUS_201_Future_Skills_II_TM_2024_1_FuS_II_SM_teachers_351c9413@edu.accadis.com",
          courseGroupEmail:
            "FUS_201_Future_Skills_II_TM_2024_1_FuS_II_SM_79ef85b1@edu.accadis.com",
          teacherFolder: {
            id: "18pf8kRGCSztScRjwAYjCI1E6bph1wwS_XmZ7S_nl8WxT5CP2kcUlMqn3ScOqy4CDPkDejV3Z",
            title: "FUS 201 Future Skills II TM 2024-1 FuS II-SM",
            alternateLink:
              "https://drive.google.com/drive/folders/18pf8kRGCSztScRjwAYjCI1E6bph1wwS_XmZ7S_nl8WxT5CP2kcUlMqn3ScOqy4CDPkDejV3Z",
          },
          guardiansEnabled: false,
          calendarId: "c_classroom8cf51a06@group.calendar.google.com",
          gradebookSettings: {
            calculationType: "TOTAL_POINTS",
            displaySetting: "HIDE_OVERALL_GRADE",
          },
        },
        isValidClassroom: true,
        type: "MODULE",
        teachers: [
          {
            id: "1",
            name: "Transrezult Admin",
            isOwner: false,
            class: "bg-[#fdf5e6]",
            givenName: "Transrezult",
            familyName: "Admin",
            fullName: "Transrezult Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "2",
            name: "Dario Echter",
            isOwner: false,
            class: "bg-[#fadadd]",
            givenName: "Dario",
            familyName: "Echter",
            fullName: "Dario Echter",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
          {
            id: "3",
            name: "Classroom Admin ",
            isOwner: true,
            class: "bg-[#fdf5e6]",
            givenName: "Classroom",
            familyName: "Admin",
            fullName: "Classroom Admin",
            Geschlecht: " männlich",
            Gender: "intergeschlechtlich",
            Nationalität: "Deutsch",
            Languages: ["ger", "eng", "rus"],
            Age: "25",
            birthday: "01.01.1996",
            Country: "Deutschland",
            City: "Berlin",
            Street: "Karl-Marx-Str. 1",
            Zip: "12345",
            Phone: "+49 123 456 789",
            Email: "asd@gmail.com",
            Hobby: "Football",
          },
        ],
        students: [
          {
            id: "1",
            name: "Johan Müller",
            email: "",
            displayName: "Bobr Kurwa",
            details: "Details",
            givenName: "Johan ",
            familyName: "Müller",
            fullName: "Johan Müller",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "2",
            name: "Voldemar Koch",
            email: "",
            displayName: "Johan Popierdolilo",
            details: "Details",
            givenName: "Voldemar ",
            familyName: "Koch",
            fullName: "Voldemar Koch",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
          {
            id: "3",
            name: "Vitold Pechke",
            email: "",
            displayName: "Dzień Dobry",
            details: "Details",
            givenName: "Vitold ",
            familyName: "Pechke",
            fullName: "Vitold Pechke",
            Geschlecht: " männlich",
            Gender: "androgyn",
            Nationalität: "Deutsch",
            Languages: ["ger", "dut", "tur"],
            Age: "25",
            birthday: "05.05.1991",
            Country: "Deutschland",
            City: "Düsseldorf",
            Street: "Die Straße 1",
            Zip: "23451",
            Phone: "+49 123 456 789",
            Email: "dfr@gmail.com",
            Hobby: "Hockey",
          },
        ],
      },
    ]);
    return {
      classrooms,
    };
  }
);
